characters = [
    {
        "index": 0,
        "class": "soulfist",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 1,
        "class": "deathblade",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 2,
        "class": "deathblade",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 3,
        "class": "deathblade",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 4,
        "class": "deathblade",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 5,
        "class": "slayer",  
        "ilvl-endless": 1610,
        "ilvl-aor": 1610,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 6,
        "class": "reaper",  
        "ilvl-endless": 1610,
        "ilvl-aor": 1610,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 7,
        "class": "scrapper",  
        "ilvl-endless": 1610,
        "ilvl-aor": 1610,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 8,
        "class": "summoner",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 9,
        "class": "glaivier",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 10,
        "class": "wardancer",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 11,
        "class": "breaker",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 12,
        "class": "sorceress",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 13,
        "class": "paladin",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 14,
        "class": "bard",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 15,
        "class": "scouter",  
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "lopang": False,    
        "guildDonation": True,
        "rapport": False,
    },
]
